name: salgado-care-backend
services:
  api:
    build: .
    container_name: salgado-care-api
    restart: always
    ports:
      - "7002:7002"
    environment:
      - PORT=7002
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: salgado-care-db
    restart: always
    env_file:
      - .env
    ports:
      - "7003:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
